"""categories and products tables

Revision ID: 22d4ec9d520c
Revises: 
Create Date: 2023-10-04 00:52:12.575260

"""
import os
import json
from typing import Sequence, Union
from datetime import datetime

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '22d4ec9d520c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('products')
    op.drop_table('categories')
    # ### end Alembic commands ###


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    categories = op.create_table('categories',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    products = op.create_table('products',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', mysql.VARCHAR(length=200), nullable=False),
    sa.Column('description', mysql.TEXT(), nullable=True),
    sa.Column('price', mysql.FLOAT(), nullable=False),
    sa.Column('discount_percentage', mysql.FLOAT(), nullable=False, default=0),
    sa.Column('rating', mysql.FLOAT(), nullable=False),
    sa.Column('stock', mysql.INTEGER(), autoincrement=False, nullable=False, default=0),
    sa.Column('brand', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('category_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=False, default=datetime.utcnow()),
    sa.Column('updated_at', mysql.DATETIME(), nullable=False, default=datetime.utcnow()),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], name='products_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )

    # seed products & categories data
    with(open(os.path.join(os.path.dirname(__file__), "../../db/data/categories.json"))) as f:
        categories_data = f.read()
    
    op.bulk_insert(categories, json.loads(categories_data))

    with(open(os.path.join(os.path.dirname(__file__), "../../db/data/products.json"))) as f:
        products_data = f.read()
    
    op.bulk_insert(products, json.loads(products_data))
    # ### end Alembic commands ###
