"""inventories table

Revision ID: 5c65d0c0ad01
Revises: 22d4ec9d520c
Create Date: 2023-10-09 01:06:26.365161

"""
from typing import Sequence, Union
from datetime import datetime

from alembic import op
import sqlalchemy as sa
from sqlalchemy.orm import Session
from sqlalchemy.dialects import mysql
from fastapi import Depends

from db.db_setup import get_db
from api.utils.inventories import seed_inventory

# revision identifiers, used by Alembic.
revision: str = '5c65d0c0ad01'
down_revision: Union[str, None] = '22d4ec9d520c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


db = get_db()

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inventories',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('quantity', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('product_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=False, default=datetime.utcnow()),
    sa.Column('updated_at', mysql.DATETIME(), nullable=False, default=datetime.utcnow()),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name='inventories_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###


    seed_inventory(next(db))


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('inventories')
    # ### end Alembic commands ###
